* Що це?
Це репозиторій, що містить роботу мого дідуся, Юрія Петровича Булки, яку він не встиг закінчити.

* Для чого це тут?
Ми вирішили зробити текст відкритим як для читання, так і до поліпшення. Платформою для технічної регуляції цього ми
обрали git, згодом додам детальніший опис, як він працює. Вам тільки важливо знати, що це для того, щоб ви, за бажанням,
могли додати свої виправлення чи покращення в роботу, і щоб це було технічно добре влаштовано.

* Що з цим буде далі?
Наразі в планах просто відредагувати цю роботу насамперед із технічного, а трохи, може, й з лінгвістичного боку, але
ніяких суттєвих змін не робити. Разом із тим, якщо ви маєте які-небудь побажання чи хочете долучитись до того, щоб
дописати роботу до кінця, для цього усе готово. Зв’яжіться з нами, і ми розповімо, як це технічно правильно зробити.

* Дописувати чи не дописувати?
І так і ні. Оригінальний дідусевий текст буде збережено в історії цього репозиторію (кожна зміна накладається на
попередню версію, але старі версії не зникають). Тому будь-яка робота з текстом є корисною (якщо вона є цінною),
навіть коли шматки тексту витираються. Оригінальний текст завжди буде доступним.

* А як з авторським правом?
Вміст репозиторію доступний на умовах ліцензії [[http://creativecommons.org/licenses/by-sa/3.0/][Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)]]. Це
означає (в спрощеному викладі), що вам надається право використовувати та розповсюджувати оригінальні та модифіковані
вами копії тексту за умови, що ви вказуєте усіх авторів тексту перед вами, а також, що розповсюджувані вами копії
матимуть ту саму ліцензію. Усі деталі ліцензії ви можете отримати за наведеним лінком до ліцензії.
