* Що це?
Це репозиторій, що містить роботу мого дідуся, Юрія Петровича Булки, яку він не встиг закінчити.

** Для чого це тут?
Ми вирішили зробити текст відкритим (вільнодоступним) як для читання, так і до поліпшення. Платформою для технічної регуляції цього ми обрали git, бо з ним нам найзручніше працювати. Згодом, можливо, ми перемістимо текст у Вікіджерела.

** А як з авторським правом?
Вміст репозиторію доступний на умовах ліцензії [[http://creativecommons.org/licenses/by-sa/3.0/][Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)]]. Це означає (в спрощеному викладі), що вам надається право використовувати та розповсюджувати оригінальні та модифіковані вами копії тексту за умови, що ви вказуєте усіх авторів тексту перед вами, а також, що розповсюджувані вами копії матимуть ту саму ліцензію. Усі деталі ліцензії ви можете отримати за наведеним лінком до ліцензії.

* В якому форматі текст?
Тут все дуже просто: це прості текстові файли, такі самі, як ті, що мають хвіст «.txt». Різниця тільки в тому, що в цих файлах можна додатково вставляти позначки, що дають змогу перетворити їх такі формати, як PDF (для друку) чи HTML (для вебу), при тому зовсім не переймаючись виглядом документа, а лише його структурою. Тому ці файли мають хвіст не «.txt» а «.org» (такий хвіст вказує на назву програми [[http://uk.wikipedia.org/wiki/Org-mode][Org-mode]], яка й перетворює файли в різноманітні формати).

Тому ви можете редагувати ці файли будь-яким редактором, що орієнтований на прості (неформатовані) текстові файли.
